import CommentaireRenderer from "../../ChampEditable/CommentaireRenderer";
import HeureEditor from "../../ChampEditable/HeureEditor";

const CyclesAppelsObsColumnDefinition = () => {
  return [
    {
      headerName: "Heure",
      field: "heure",
      width: 140,
      minWidth: 140,
      maxWidth: 200,
      editable: true,
      cellRenderer: CommentaireRenderer,
      cellEditor: HeureEditor,
      autoHeight: true,
      cellStyle: { fontWeight: "bold" },
    },
    {
      headerName: "Grp-1",
      field: "grp_1",
      width: 100,
      minWidth: 80,
      resizable: true,
      cellRenderer: "agCheckboxCellRenderer",
      cellEditor: "agCheckboxCellEditor",
      editable: true,
    },
    {
      headerName: "Grp-2",
      field: "grp_2",
      width: 100,
      minWidth: 80,
      resizable: true,
      cellRenderer: "agCheckboxCellRenderer",
      cellEditor: "agCheckboxCellEditor",
      editable: true,
    },
    {
      headerName: "Grp-3",
      field: "grp_3",
      width: 100,
      minWidth: 80,
      resizable: true,
      cellRenderer: "agCheckboxCellRenderer",
      cellEditor: "agCheckboxCellEditor",
      editable: true,
    },
    {
      headerName: "Grp-4",
      field: "grp_4",
      width: 100,
      minWidth: 80,
      resizable: true,
      cellRenderer: "agCheckboxCellRenderer",
      cellEditor: "agCheckboxCellEditor",
      editable: true,
    },
    {
      headerName: "Grp-5",
      field: "grp_5",
      width: 100,
      minWidth: 80,
      resizable: true,
      cellRenderer: "agCheckboxCellRenderer",
      cellEditor: "agCheckboxCellEditor",
      editable: true,
    },
    {
      headerName: "Grp-6",
      field: "grp_6",
      width: 100,
      minWidth: 80,
      resizable: true,
      cellRenderer: "agCheckboxCellRenderer",
      cellEditor: "agCheckboxCellEditor",
      editable: true,
    },
    {
      headerName: "Grp-7",
      field: "grp_7",
      width: 100,
      minWidth: 80,
      resizable: true,
      cellRenderer: "agCheckboxCellRenderer",
      cellEditor: "agCheckboxCellEditor",
      editable: true,
    },
    {
      headerName: "Grp-8",
      field: "grp_8",
      width: 100,
      minWidth: 80,
      resizable: true,
      cellRenderer: "agCheckboxCellRenderer",
      cellEditor: "agCheckboxCellEditor",
      editable: true,
    },
    {
      headerName: "Grp-9",
      field: "grp_9",
      width: 100,
      minWidth: 80,
      resizable: true,
      cellRenderer: "agCheckboxCellRenderer",
      cellEditor: "agCheckboxCellEditor",
      editable: true,
    },
    {
      headerName: "Grp-10",
      field: "grp_10",
      width: 100,
      minWidth: 80,
      resizable: true,
      cellRenderer: "agCheckboxCellRenderer",
      cellEditor: "agCheckboxCellEditor",
      editable: true,
    },
    {
      headerName: "Grp-11",
      field: "grp_11",
      width: 100,
      minWidth: 80,
      resizable: true,
      cellRenderer: "agCheckboxCellRenderer",
      cellEditor: "agCheckboxCellEditor",
      editable: true,
    },
    {
      headerName: "SIGMA",
      field: "grp_sigma",
      flex: 1,
      cellRenderer: "agCheckboxCellRenderer",
      cellEditor: "agCheckboxCellEditor",
      editable: true,
    },
  ];
};

export default CyclesAppelsObsColumnDefinition;
