export const Taches = {
  taches: [
    [
      "T2 Démarrage & Init",
      "T6 Gestion des tempos",
      "T36 Gestion appel ext",
      "T41 Gestion sockets",
    ],
    [
      "T3 ModBus esclave",
      "T13 Enregistrement",
      "T37 Surveil appel RC",
      "T42 Serveur Modbus",
    ],
    [
      "T4 Gestion pile TCP",
      "T16 Acq & traits spé",
      "T39 Gestion vidage piles",
      "T43 ModBus TCP",
    ],
    [
      "T5 Gestion pile TCP(10ms)",
      "T17 Dialogue Shut",
      "T40 Serveur FTP",
      "T63 Gestion mémoire flash",
    ],
  ],
};

export const DefautOptions = [
  "",
  "Alerte remplissage mémoire",
  "Arrêt acquisition",
  "Arrêt enregistrement",
  "Arrêt enregistreur",
  "Arrêt transfert SHUT",
  "Défaut date initialisation",
  "Défaut dialogue ADSL",
  "Défaut dialogue série",
  "Dérive horloge",
  "Dysfonctionnement configuration VisuNet",
  "Dysfonctionnement enregistreur",
  "Dysfonctionnement téléchargement programme",
  "FTP HS et tâches ok",
  "Ne répond pas au ping",
  "Paramètrage Shut",
  "Plus d'enregistrements à 15s",
  "Reset",
];
export const CauseOptions = [
  "",
  "Maintenance station",
  "Arrêt enregistreur",
  "Changement heure été hiver",
  "Défaut paramétrage",
  "Incident AutoShut",
  "Mise à jour distante du logiciel",
  "Mise à jour du matériel",
  "Mise à jour locale du logiciel",
  "Non déterminée",
  "Panne alimentation",
  "Panne ligne ADSL",
  "Panne ligne RC",
  "Panne logiciel enregistreur fonctionnement partiel",
  "Panne matériel enregistreur",
  "Panne routeur",
  "Plantage enregistreur",
  "Préventif",
  "Problème transmission",
  "Tâche 13 (enregistrement) bloquée",
  "Tâche 16 (acquisition) bloquée",
  "Tâche 17 (dialogue Visu, shut) bloquée",
  "Tâche 40 (FTP, vidage) bloquée",
  "Tâche 41 (dialogue Visu en TCP) bloquée",
  "Tâche autre bloquée",
  "Tâches 42, 43 (dialogue ModbusTCP) bloquée",
  "Travaux",
];
export const RemedeOptions = [
  "",
  "Fin maintenance sur station",
  "Arrêt / marche logiciel (@bloquer, @go)",
  "Arrêt / marche matériel (interrupteur)",
  "Echange standard enregistreur",
  "Effacer mémoire d'enregistrement",
  "Fin intervention ITEN sur enregistreur",
  "Fin mise à jour du logiciel",
  "Fin travaux",
  "Initialiser l'enregistreur (@init)",
  "Mise à jour paramétrage",
  "Mise à l'heure enregistreur",
  "Plus de défaut",
  "Rechargement config (VisuShut)",
  "Rechargement distant programme enregistreur",
  "Rechargement local programme enregistreur",
  "Relance enregistreur (@go)",
  "Retour alimentation",
];
export const Meteo = ["mixte"];
export const Evt = ["Non"];
export const PerteCrit = ["Oui"];
